// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJhxmDxyeJnur1O01gfdjX_20zTedxZWw',
    appId: '1:1002589397108:web:794c9828b65d0c6c967121',
    messagingSenderId: '1002589397108',
    projectId: 'fir-practise-67120',
    authDomain: 'fir-practise-67120.firebaseapp.com',
    storageBucket: 'fir-practise-67120.firebasestorage.app',
    measurementId: 'G-YMCNW727EK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1nHq8V00LhR5m1G6vNg66ABS0eJwpkiQ',
    appId: '1:1002589397108:android:67bbfdaf25e62c2e967121',
    messagingSenderId: '1002589397108',
    projectId: 'fir-practise-67120',
    storageBucket: 'fir-practise-67120.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZZg8mjkBNvkEIUzk6Nr7mbzEIBTDLVTw',
    appId: '1:1002589397108:ios:0aba6929b7097bc8967121',
    messagingSenderId: '1002589397108',
    projectId: 'fir-practise-67120',
    storageBucket: 'fir-practise-67120.firebasestorage.app',
    iosBundleId: 'com.example.ostadFlutterSazu',
  );
}
